version: '3.9'
services:

  meilisearch:
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    build:
      context: ./apps/meilisearch/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '7700:7700'
    networks:
      - hana_network

  # strapi:
  #   container_name: strapi
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     DATABASE_SSL: ${DATABASE_SSL}
  #     CLOUDINARY_NAME: ${CLOUDINARY_NAME}
  #     CLOUDINARY_KEY: ${CLOUDINARY_KEY}
  #     CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
  #     HOST: ${HOST}
  #     PORT: ${PORT}
  #     APP_KEYS: ${APP_KEYS}
  #     API_TOKEN_SALT: ${API_TOKEN_SALT}
  #     ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
  #     TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
  #     JWT_SECRET: ${JWT_SECRET}
  #     PUBLIC_URL: ${PUBLIC_URL}
  #     MEILI_HOST: meilisearch:7700
  #     MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
  #   build:
  #     context: ./apps/api
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 1337:1337
  #   networks:
  #     - hana_network
  #   depends_on:
  #     - meilisearch

networks:
  hana_network:
    external: true
